#!/bin/bash

amazon-linux-extras install nginx1 -y

cat > /etc/systemd/system/saga-recommender-api.service << 'EOF'
[Unit]
Description=Go Application as a Service

[Service]
User=ec2-user

WorkingDirectory=/app/

ExecStart=/app/saga-recommender-api
SuccessExitStatus=143
TimeoutStopSec=10
Restart=on-failure
RestartSec=5
EnvironmentFile=-/app/env
         
[Install] 
WantedBy=multi-user.target 
EOF